language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "pypy"

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - "pip install -M pytest"
    - "python setup.py develop"

before_script:
    - "mysql -e 'create database test_pymysql  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -e 'create database test_pymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "cp .travis.databases.json pymysql/tests/databases.json"

script: "py.test pymysql/tests"
