language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

install:
    - "pip install -M pytest"
    - "python setup.py develop"

before_script:
    - "mysql -e 'create database test_pymysql;'"
    - "mysql -e 'create database test_pymysql2;'"
    - "cp .travis.databases.json pymysql/tests/databases.json"

test_script: "py.test pymysql/tests"
