sudo: false
language: python
python: "3.4"
cache:
    directories:
        - ${HOME}/mysql
    pip: true


env:
    matrix:
        - TOX_ENV=py26
        - TOX_ENV=py27
        - TOX_ENV=py33
        - TOX_ENV=py34
        - TOX_ENV=pypy
        - TOX_ENV=pypy3

matrix:
    include:
        - addons:
             mariadb: 5.5
          env: TOX_ENV=py27
        - addons:
             mariadb: 10.0
          env: TOX_ENV=py33
        - addons:
             mariadb: 10.1
          env: TOX_ENV=py34
        - env:
             - TOX_ENV=py34
             - DB=5.6.26
          addons:
              apt:
                 packages:
                     - libaio-dev
          python: 3.3
        - env:
             - TOX_ENV=py34
             - DB=5.7.8-rc
          addons:
              apt:
                 packages:
                     - libaio-dev
          python: 3.4

# different py version from 5.6 and 5.7 as cache seems to be based on py version

# http://dev.mysql.com/downloads/mysql/5.7.html has latest development release version

# really only need libaio1 however libaio-dev is whitelisted for container builds and liaio1 isn't

install:
    - pip install -U tox

before_script:
    - if [ ! -z "${DB}" ]; then
          ./.travis.initialize.db.sh;
      fi
    - "mysql -e 'create database test_pymysql  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -e 'create database test_pymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -e 'select VERSION();'"

script:
    - tox -e $TOX_ENV

after_failure:
    - cat /tmp/mysql.err
