sudo: false
language: python
python: "3.4"
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - TOX_ENV=pypy3

matrix:
   include:
     - addons:
          mariadb: 5.5
       env: TOX_ENV=py27
     - addons:
          mariadb: 10.0
       env: TOX_ENV=py33
     - addons:
          mariadb: 10.1
       env: TOX_ENV=py34

install:
    - pip install -U tox

before_script:
    - "mysql -e 'create database test_pymysql  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -e 'create database test_pymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -e 'select VERSION();'"
    - cp .travis.databases.json pymysql/tests/databases.json

script: tox -e $TOX_ENV
