name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: flake8
        run: |
          pip install flake8
          flake8 pymysql
